# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-08 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CmdbGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=30)),
                ('comm', models.CharField(max_length=300, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
            ],
        ),
        migrations.CreateModel(
            name='CmdbHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30)),
                ('pubip', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50, null=True)),
                ('cpu_count', models.CharField(max_length=4, null=True)),
                ('cpu_info', models.CharField(max_length=60, null=True)),
                ('mem_info', models.CharField(max_length=60, null=True)),
                ('system_info', models.CharField(max_length=60, null=True)),
                ('comm', models.CharField(max_length=300, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
                ('group', models.ManyToManyField(null=True, to='devops.CmdbGroup')),
            ],
        ),
    ]
