# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-11 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0003_auto_20170309_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='host',
            field=models.ManyToManyField(to='devops.CmdbHost'),
        ),
    ]
