# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-12 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0004_idc_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='remote_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=6)),
                ('comm', models.CharField(max_length=300, verbose_name='\u7528\u6237\u63cf\u8ff0\u4fe1\u606f')),
                ('auth_choice', models.CharField(choices=[('password', 'password'), ('ssh-key', 'ssh-key')], max_length=10)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devops.CmdbHost')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='host',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
