# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-12 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0005_auto_20170312_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remote_user',
            name='comm',
        ),
        migrations.AlterField(
            model_name='remote_user',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
