# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0006_auto_20170312_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRemote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostip', models.CharField(max_length=20)),
                ('localfile', models.CharField(max_length=60)),
                ('remotefile', models.CharField(max_length=60)),
                ('action_choice', models.CharField(choices=[('upload', '\u4e0a\u4f20'), ('download', '\u4e0b\u8f7d')], max_length=8)),
                ('Ttime', models.DateTimeField(auto_now_add=True)),
                ('resultAction', models.CharField(max_length=8)),
            ],
        ),
    ]
