# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-24 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0007_fileremote'),
    ]

    operations = [
        migrations.CreateModel(
            name='runCmdLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostList', models.CharField(max_length=10)),
                ('cmd', models.CharField(max_length=80)),
                ('cmdresult', models.CharField(max_length=500)),
                ('Ttime', models.DateTimeField(auto_now_add=True)),
                ('API', models.CharField(max_length=10)),
            ],
        ),
    ]
