# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-27 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0009_auto_20170324_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='pageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CmdbHostPage', models.CharField(max_length=4, null=True)),
                ('CmdbGroupPage', models.CharField(max_length=4, null=True)),
                ('IDCPage', models.CharField(max_length=4, null=True)),
                ('remote_userPage', models.CharField(max_length=4, null=True)),
                ('FileRemotePage', models.CharField(max_length=4, null=True)),
                ('runCmdLogPage', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='runcmdlog',
            name='hostList',
            field=models.CharField(max_length=80),
        ),
    ]
