# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-29 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0010_auto_20170327_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmdbhost',
            name='cpu_count',
        ),
        migrations.AddField(
            model_name='cmdbhost',
            name='cpu_Physical',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='cmdbhost',
            name='cpu_core',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='cmdbhost',
            name='cpu_processor',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='cmdbhost',
            name='system_kernel',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
