# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0011_auto_20170329_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='diskUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesystem', models.CharField(max_length=120, verbose_name='\u6587\u4ef6\u7cfb\u7edf')),
                ('total', models.CharField(max_length=20, verbose_name='\u603b\u7a7a\u95f4\u5927\u5c0f')),
                ('used', models.CharField(max_length=20, verbose_name='\u4f7f\u7528\u60c5\u51b5')),
                ('avail', models.CharField(max_length=20, verbose_name='\u53ef\u7528\u60c5\u51b5')),
                ('usep', models.CharField(max_length=5, verbose_name='\u4f7f\u7528\u767e\u5206\u6bd4')),
                ('mounted', models.CharField(max_length=50, verbose_name='\u6302\u8f7d\u5230\u54ea')),
                ('Ttime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devops.CmdbHost')),
            ],
        ),
    ]
