# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0013_updatedisk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPaddr', models.CharField(max_length=40, verbose_name='ip\u5730\u5740')),
                ('AppName', models.CharField(max_length=50, verbose_name='\u5e94\u7528\u540d\u79f0')),
                ('AppPort', models.CharField(max_length=6, verbose_name='\u5e94\u7528\u76d1\u542c\u7aef\u53e3\u53f7')),
                ('AppMasterName', models.CharField(max_length=20, verbose_name='\u4e3b\u8fdb\u7a0b\u540d\u79f0')),
                ('killApp', models.CharField(max_length=30, verbose_name='\u6740\u6b7b\u8fdb\u7a0b')),
                ('BasePath', models.CharField(max_length=60, verbose_name='\u5e94\u7528\u7684\u542f\u52a8\u811a\u672c\u7edd\u5bf9\u8def\u5f84')),
                ('StartAction', models.CharField(max_length=30, verbose_name='\u542f\u52a8\u5e94\u7528\u65f6\u91c7\u7528\u7684\u52a8\u4f5c')),
                ('StopAction', models.CharField(max_length=30, verbose_name='\u505c\u6b62\u5e94\u7528\u91c7\u7528\u7684\u52a8\u4f5c')),
                ('RestartAction', models.CharField(max_length=30, verbose_name='\u91cd\u542f\u5e94\u7528')),
            ],
        ),
    ]
