# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0014_appctrl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appctrl',
            name='AppName',
        ),
    ]
