# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-11 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0016_remove_appctrl_killapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='app',
        ),
    ]
