# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-25 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Load01', models.CharField(max_length=10)),
                ('Load05', models.CharField(max_length=10)),
                ('Load15', models.CharField(max_length=10)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('Host', models.CharField(max_length=32, verbose_name='ipaddress')),
            ],
        ),
        migrations.CreateModel(
            name='CpuStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CpuIdle', models.FloatField()),
                ('CpuIowait', models.CharField(max_length=20)),
                ('CpuSystem', models.CharField(max_length=20)),
                ('CpuUser', models.CharField(max_length=20)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('Host', models.CharField(max_length=32, verbose_name='ipaddress')),
            ],
        ),
        migrations.CreateModel(
            name='DiskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileSystem', models.CharField(max_length=120)),
                ('Total', models.CharField(max_length=20)),
                ('Used', models.CharField(max_length=20)),
                ('Avail', models.CharField(max_length=20)),
                ('UseP', models.CharField(max_length=5)),
                ('MountedOn', models.CharField(max_length=50)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Host', models.CharField(max_length=30)),
                ('System', models.CharField(max_length=30)),
                ('Arch', models.CharField(max_length=12)),
                ('Cpulogical', models.CharField(max_length=4)),
                ('Cpupysic', models.CharField(max_length=4)),
                ('Cpu', models.CharField(max_length=50)),
                ('LocalIp', models.GenericIPAddressField(null=True, unique=True)),
                ('PubIp', models.GenericIPAddressField(null=True, unique=True)),
                ('Mac', models.CharField(max_length=22)),
                ('Comment', models.CharField(max_length=300)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(max_length=30, unique=True)),
                ('DiskInfo', models.ManyToManyField(to='MonitorDataSave.DiskInfo')),
                ('HardInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MonitorDataSave.HardInfo')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=50, verbose_name='IDC\u673a\u623f\u5730\u5740')),
                ('D1', models.CharField(max_length=50, verbose_name='\u4f4d\u4e8e\u54ea\u4e2a\u673a\u67b6')),
            ],
        ),
        migrations.CreateModel(
            name='MemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.CharField(max_length=30)),
                ('Used', models.CharField(max_length=30)),
                ('Free', models.CharField(max_length=30)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('Host', models.CharField(max_length=32, verbose_name='ipaddress')),
            ],
        ),
        migrations.CreateModel(
            name='NetInOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EthName', models.CharField(max_length=30)),
                ('InEth', models.CharField(max_length=30)),
                ('OutEth', models.CharField(max_length=30)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('Host', models.CharField(max_length=32, verbose_name='ipaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SwapInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.CharField(max_length=30)),
                ('Used', models.CharField(max_length=30)),
                ('Free', models.CharField(max_length=30)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('Host', models.CharField(max_length=32, verbose_name='ipaddress')),
            ],
        ),
        migrations.AddField(
            model_name='hardinfo',
            name='HostName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorDataSave.HostName'),
        ),
        migrations.AddField(
            model_name='hardinfo',
            name='IDC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MonitorDataSave.IDC'),
        ),
        migrations.AddField(
            model_name='hardinfo',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MonitorDataSave.Status'),
        ),
        migrations.AddField(
            model_name='hardinfo',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MonitorDataSave.group'),
        ),
        migrations.AddField(
            model_name='diskinfo',
            name='Host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitorDataSave.HostName'),
        ),
    ]
