# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-24 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0002_auto_20170424_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='ip_addr',
            field=models.GenericIPAddressField(),
        ),
    ]
