# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-05 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0003_auto_20170424_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('script', 'RunScript')], default='email', max_length=128, verbose_name='\u52a8\u4f5c\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='action',
            name='notifiers',
            field=models.ManyToManyField(blank=True, to='Monitor.NotifiersUser', verbose_name='\u901a\u77e5\u5bf9\u8c61'),
        ),
        migrations.AddField(
            model_name='action',
            name='scritp',
            field=models.TextField(default="echo'hello'", verbose_name='\u811a\u672c\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='action',
            name='sendmsgBody',
            field=models.TextField(null=True, verbose_name='\u90ae\u4ef6\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='action',
            name='sendmsgSub',
            field=models.TextField(default='\u544a\u8b66\u90ae\u4ef6', verbose_name='\u90ae\u4ef6\u53d1\u9001\u4e3b\u9898'),
        ),
    ]
