# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-06 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0004_auto_20170705_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='operations',
        ),
    ]
