# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-06 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0005_remove_action_operations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='condition',
        ),
    ]
